set(BUILD_KERNEL_OPTIONS )
set(BUILD_DRIVER_OPTIONS )

if ("$ENV{VA_BITS}" STREQUAL "" AND NOT VA_BITS)
    list(APPEND BUILD_KERNEL_OPTIONS "VA_BITS=48")
    list(APPEND BUILD_DRIVER_OPTIONS "-DgcdVA_BITS=48")
else()
    if (NOT VA_BITS)
        set(VA_BITS $ENV{VA_BITS})
    endif()
    list(APPEND BUILD_KERNEL_OPTIONS "VA_BITS=${VA_BITS}")
    list(APPEND BUILD_DRIVER_OPTIONS "-DgcdVA_BITS=${VA_BITS}")
endif()

if ("$ENV{ARCH_TYPE}" STREQUAL "" AND NOT ARCH_TYPE)
    list(APPEND BUILD_KERNEL_OPTIONS "ARCH_TYPE=x86")
else()
    if (NOT ARCH_TYPE)
        set(ARCH_TYPE $ENV{ARCH_TYPE})
    endif()
    list(APPEND BUILD_KERNEL_OPTIONS "ARCH_TYPE=${ARCH_TYPE}")
endif()

if ("$ENV{USE_LINUX_PCIE}" STREQUAL "1" OR USE_LINUX_PCIE)
    list(APPEND BUILD_KERNEL_OPTIONS "USE_LINUX_PCIE=1")
    list(APPEND BUILD_DRIVER_OPTIONS "-DUSE_LINUX_PCIE=1")
endif()
if ("$ENV{MMU_VERSION_2}" STREQUAL "1" OR MMU_VERSION_2)
    list(APPEND BUILD_KERNEL_OPTIONS "MMU_VERSION_2=1")
    list(APPEND BUILD_DRIVER_OPTIONS "-DgcdMMU_VERSION_2=1")
endif()
if ("$ENV{ENABLE_40BITS_VA}" STREQUAL "1" OR ENABLE_40BITS_VA)
    list(APPEND BUILD_KERNEL_OPTIONS "VIVANTE_ENABLE_40BITS_VA=1")
    list(APPEND BUILD_DRIVER_OPTIONS "-DVIVANTE_ENABLE_40BITS_VA=1")
endif()
if ("$ENV{FPGA_BUILD}" STREQUAL "1" OR FPGA_BUILD)
    list(APPEND BUILD_KERNEL_OPTIONS "FPGA_BUILD=1")
    list(APPEND BUILD_DRIVER_OPTIONS "-DFPGA_BUILD=1")
endif()
if (BUILD_QEMU)
    list(APPEND BUILD_KERNEL_OPTIONS "BUILD_CMODEL_QEMU=1")
    list(APPEND BUILD_DRIVER_OPTIONS "-DCMODEL_QEMU=1")
endif()
if ("$ENV{DRM_KMD_QEMU}" STREQUAL "1" OR DRM_KMD_QEMU)
    list(APPEND BUILD_KERNEL_OPTIONS "DRM_KMD_QEMU=1")
    list(APPEND BUILD_DRIVER_OPTIONS "-DDRM_KMD_QEMU")
endif()
if ("$ENV{ENABLE_HMM}" STREQUAL "1")
    list(APPEND BUILD_KERNEL_OPTIONS "ENABLE_HMM=1")
    list(APPEND BUILD_DRIVER_OPTIONS "-DgcdENABLE_HMM=1")
else()
    list(APPEND BUILD_KERNEL_OPTIONS "ENABLE_HMM=0")
    list(APPEND BUILD_DRIVER_OPTIONS "-DgcdENABLE_HMM=0")
endif()

if (BUILD_LINUX)
    if ("$ENV{KERNEL_DRIVER_BUILD_TYPE}" STREQUAL "debug" OR "$ENV{KERNEL_DRIVER_BUILD_TYPE}" STREQUAL "Debug" OR "${KERNEL_DRIVER_BUILD_TYPE}" STREQUAL "debug" OR "${KERNEL_DRIVER_BUILD_TYPE}" STREQUAL "Debug")
        list(APPEND BUILD_KERNEL_OPTIONS "DEBUG=1")
    endif()
endif()

macro(copy_feature_database)
    if (NOT FIXED_ARCH_TYPE)
        if (EXISTS ${AQTOOLS}/bin/gc_feature_database.h)
            if (EXISTS ${AQROOT}/hal/inc/gc_feature_database.h)
                file(REMOVE ${AQROOT}/hal/inc/gc_feature_database.h)
            endif()

            execute_process(
                COMMAND ${CMAKE_COMMAND} -E copy ${AQTOOLS}/bin/gc_feature_database.h ${AQROOT}/hal/inc/gc_feature_database.h
            )
        endif()
        if (EXISTS ${AQTOOLS}/bin/gc_vsim_configs.h)
            execute_process(
                COMMAND ${CMAKE_COMMAND} -E copy ${AQTOOLS}/bin/gc_vsim_configs.h ${AQROOT}/hal/inc/gc_vsim_configs.h
            )
        endif()
    endif()
endmacro()

copy_feature_database()
