<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WaveTraceRoot Condition="'$(WaveTraceRoot)'==''">$(MSBuildThisFileDirectory)..</WaveTraceRoot>
    <WaveTraceWriterHelperExe>$(WaveTraceRoot)\tools\bin\wvz4_writer_monitor.exe</WaveTraceWriterHelperExe>
  </PropertyGroup>

  <Target Name="CheckWaveTraceWriterHelperPrebuilt" BeforeTargets="Build">
    <Error Condition="!Exists('$(WaveTraceWriterHelperExe)')" Text="WaveTrace writer helper executable not found: $(WaveTraceWriterHelperExe)" />
  </Target>
</Project>
